server:
  port: 8090

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Auth Service Routes - Public endpoints
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:https://auth-api.edunex.app}
              predicates:
                - Path=/api/auth/**, /actuator/**

            # Subscription Service Routes
            - id: subscription-service
              uri: ${SUBSCRIPTION_SERVICE_URL:http://${SUBSCRIPTION_SERVICE_HOST:localhost}:${SUBSCRIPTION_SERVICE_PORT:8083}}
              predicates:
                - Path=/api/v1/subscription-plans/**,/api/v1/subscriptions/**,/api/v1/points/**,/api/v1/payments/**,/api/v1/webhooks/**

            # Course Service Routes
            - id: course-service
              uri: ${COURSE_SERVICE_URL:http://${COURSE_SERVICE_HOST:localhost}:${COURSE_SERVICE_PORT:8082}}
              predicates:
              - Path=/api/courses/**, /api/modules/**, /api/enrollments/**, /api/progress/**, /api/quizzes/**, /api/quiz-questions/**, /api/quiz-answers/**, /api/quiz-results/**

            # Notification Service Routes
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:http://${NOTIFICATION_SERVICE_HOST:localhost}:${NOTIFICATION_SERVICE_PORT:8084}}
              predicates:
                - Path=/api/notifications/**
          httpclient:
            ssl:
              use-insecure-trust-manager: true
              handshake-timeout: 30s

# Detailed logging configuration for development
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
